spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:board
    username: sa
    password: 1234l
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      hibernate:
        format_sql: true